language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  #- "pypy"
# command to install dependencies
install:
- pip install -r dev_requirements.txt --use-mirrors
# command to run tests
script:
- nosetests --with-coverage --cover-package=test_functions,test_regression
#after_success:
