# to use container-based infrastructure
sudo: false

language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

# Travis build the doc in a separate job, because building the doc is a
# rater long process. To separate the job, we use a test matrix that
# would run tests and build the doc for each version of python. Because
# the doc depends on MDAnalysis that is not compatible with python 3, the doc
# is actually built for python 2.7 only.
env:
  - SETUP=test
  - SETUP=doc

matrix:
    exclude:
        - env: SETUP=doc
          python: "3.3"
        - env: SETUP=doc
          python: "3.4"
        - env: SETUP=doc
          python: "3.5"


# command to install dependencies
addons:
    apt:
        packages:
            - r-base
            - ghc
            - cabal-install

before_install:
    # Tricks to avoid matplotlib error about X11:
    # 'no display name and no $DISPLAY environment variable'
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/#Starting-a-Web-Server
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    # Pandoc, as installed using the cabal program, must be in the PATH
    - export PATH=$PATH:~/.cabal/bin

# Installing pandoc and matplotlib are long processes. Using a cache allows
# to fasten the tests by reducing drastically the install time.
cache:
    directories:
        # Cache for pandoc install
        - $HOME/.cabal
        # Cache for pip, mostly to speed up matplotlib install
        - $HOME/.cache/pip

install:
    - pip install --upgrade pip
    - pip install -r dev_requirements.txt --cache-dir $HOME/.cache/pip
    - pip install matplotlib weblogo --cache-dir $HOME/.cache/pip
    - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install "mdanalysis>=0.11" --cache-dir $HOME/.cache/pip; fi
    - pip install -e .
    - if [[ $SETUP == 'doc' ]]; then pip install -r doc_requirements.txt --cache-dir $HOME/.cache/pip; fi
    - if [[ $SETUP == 'doc' ]]; then ./doc/source/install_pandoc.sh; fi


# command to run tests
script:
    - if [[ $SETUP == 'test' ]]; then nosetests -v pbxplore/tests; fi
    - if [[ $SETUP == 'test' ]]; then yes | ./run_demo1_assignation.sh; fi
    - if [[ $SETUP == 'test' ]]; then yes | ./run_demo2_statistics.sh; fi
    - if [[ $SETUP == 'test' ]]; then yes | ./run_demo2_clusters.sh; fi
    - if [[ $SETUP == 'doc' ]]; then cd doc; sphinx-build -W -b html source build/html; fi

#after_success:
