# to use container-based infrastructure
sudo: false

language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"

# command to install dependencies
addons:
    apt:
        packages:
            - r-base
install:
    - pip install --upgrade pip
    - pip install -r dev_requirements.txt
    - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install "mdanalysis>=0.11"; fi

# command to run tests
script:
    - nosetests --with-coverage --cover-package=PBlib,PDBlib test_functions.py test_regression.py

#after_success:
